### ISSUE TITLE
🐛 Bug: Filter by date not working after update to 0.260.5

### ISSUE THREAD

**Issue by joberthel** [nocodb/nocodb#10447]
### Please confirm that the bug report does ***not*** already exist

- [x] I confirm there is no existing issue for this bug.

### Steps to reproduce

I updated from 0.260.2 to 0.260.5 today. Since then I get the following error in my project.

You need a table with entries and a date field `Creation Date`. Now do an api request to get all entries with the following filter:
```
(Creation Date,ge,exactDate,2025-02-01)~and(Creation Date,le,exactDate,2025-02-09 23:59:59+00:00)
```

I get a 400 error response:
```
{ "msg": "d.match is not a function" }
```

### Desired Behavior

Return the entries like before.

### Project Details

Node: **v22.13.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.260.5**

**Comment by fendy3002** [comment]
Should be fixed with https://github.com/nocodb/nocodb/pull/10445
