### ISSUE TITLE
blank page after update to 301 ver

### ISSUE THREAD

**Issue by derev0x** [nocodb/nocodb#12852]
after update to 301 version i have blank start page (dash board).
In html i see error:
`Uncaught TypeError: crypto.randomUUID is not a function at DDFdVqDc.js:242:48224`

nocodb runing in docker on ubuntu 24.

`docker run -d --name nocodb-postgres \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
-e NC_DB="pg://127.0.0.1:5432?u=111&p=111&d=nocodb" \
-e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
-e NC_ALLOW_LOCAL_HOOKS="true" \
nocodb/nocodb:latest`

**Comment by mertmit** [comment]
We already created a fix for this https://github.com/nocodb/nocodb/issues/12842
We will release a hotfix asap, meanwhile moving to https resolved issue for our other users, you can check the thread.
